<a href="https://colab.research.google.com/github/obaidsayyed/Data_Analysis_Launchspring/blob/main/Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd
df=pd.read_csv('movies_raw_dataset.csv')
df.head()

,id,title,duration,MPA,rating,votes,meta_score,description,movie_link,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,filming_locations,production_companies,awards_content,genres,languages
0,tt10208198,"The Gangster, the Cop, the Devil",1h 49m,Not Rated,7.0,28K,65.0,A crime boss teams up with a cop to track down...,https://www.imdb.com/title/tt10208198/,['Lee Won-tae'],...,"$78,655","$25,775,371","$216,494",2019-05-15,['South Korea'],"['Seoul, South Korea']","['Kiwi Media Group', 'Acemaker Movieworks', 'B...","Awards, 1 win & 2 nominations total","['True Crime', 'Action', 'Crime', 'Thriller']","['Korean', 'English']"
1,tt3960412,Popstar: Never Stop Never Stopping,1h 27m,R,6.7,71K,68.0,When it becomes clear that his solo album is a...,https://www.imdb.com/title/tt3960412/,"['Andy Samberg', 'Akiva Schaffer', 'Jorma Tacc...",...,"$4,698,715","$9,680,029","$9,639,125",2016-06-03,"['United States', 'China']",NaN,"['Universal Pictures', 'Perfect World Pictures...","Awards, 1 win & 6 nominations total","['Mockumentary', 'Raunchy Comedy', 'Comedy', '...",['English']
2,tt1001508,He's Just Not That Into You,2h 9m,PG-13,6.4,188K,47.0,This Baltimore-set movie of interconnecting st...,https://www.imdb.com/title/tt1001508/,"['Abby Kohn', 'Marc Silverstein', 'Greg Behren...",...,"$27,785,487","$178,866,158","$93,953,653",2009-02-06,"['Germany', 'United States']","['Handy Market - 2514 W. Magnolia Boulevard, B...","['New Line Cinema', 'Flower Films (II)', 'Inte...","Awards, 1 win & 4 nominations total","['Feel-Good Romance', 'Romantic Comedy', 'Come...",['English']
3,tt0038303,Anna and the King of Siam,2h 8m,Approved,7.0,2.8K,NaN,"In 1862, a young Englishwoman becomes royal tu...",https://www.imdb.com/title/tt0038303/,"['Talbot Jennings', 'Sally Benson', 'Margaret ...",...,NaN,NaN,NaN,1946-09-06,['United States'],['Los Angeles County Arboretum & Botanic Garde...,['Twentieth Century Fox'],"Won 2 Oscars, 6 wins & 6 nominations total","['Period Drama', 'Biography', 'Drama', 'Romance']",['English']
4,tt1401152,Unknown,1h 53m,PG-13,6.8,273K,56.0,When a man awakens from a coma only to discove...,https://www.imdb.com/title/tt1401152/,"['Oliver Butcher', 'Stephen Cornwell', 'Didier...",...,"$21,856,389","$135,710,029","$63,686,397",2011-02-18,"['United States', 'Germany', 'United Kingdom',...","['Tresor, Berlin, Germany (night club scene)']","['Dark Castle Entertainment', 'Panda Productio...","Awards, 3 nominations total","['Action', 'Mystery', 'Thriller']","['English', 'German', 'Turkish', 'Arabic']"

In [63]:

df.columns

Index(['id', 'title', 'duration', 'MPA', 'rating', 'votes', 'meta_score',
       'description', 'movie_link', 'writers', 'directors', 'stars', 'budget',
       'opening_weekend_gross', 'gross_worldwide', 'gross_us_canada',
       'release_date', 'countries_origin', 'filming_locations',
       'production_companies', 'awards_content', 'genres', 'languages'],
      dtype='object')

In [64]:
df.describe()

             rating    meta_score
count  59181.000000  15533.000000
mean       6.162731     59.071203
std        1.070630     17.403032
min        1.000000      1.000000
25%        5.500000     47.000000
50%        6.300000     61.000000
75%        6.900000     72.000000
max       10.000000    100.000000

In [65]:
df.shape

(63249, 23)

In [66]:
df.dropna()

,id,title,duration,MPA,rating,votes,meta_score,description,movie_link,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,filming_locations,production_companies,awards_content,genres,languages
2,tt1001508,He's Just Not That Into You,2h 9m,PG-13,6.4,188K,47.0,This Baltimore-set movie of interconnecting st...,https://www.imdb.com/title/tt1001508/,"['Abby Kohn', 'Marc Silverstein', 'Greg Behren...",...,"$27,785,487","$178,866,158","$93,953,653",2009-02-06,"['Germany', 'United States']","['Handy Market - 2514 W. Magnolia Boulevard, B...","['New Line Cinema', 'Flower Films (II)', 'Inte...","Awards, 1 win & 4 nominations total","['Feel-Good Romance', 'Romantic Comedy', 'Come...",['English']
4,tt1401152,Unknown,1h 53m,PG-13,6.8,273K,56.0,When a man awakens from a coma only to discove...,https://www.imdb.com/title/tt1401152/,"['Oliver Butcher', 'Stephen Cornwell', 'Didier...",...,"$21,856,389","$135,710,029","$63,686,397",2011-02-18,"['United States', 'Germany', 'United Kingdom',...","['Tresor, Berlin, Germany (night club scene)']","['Dark Castle Entertainment', 'Panda Productio...","Awards, 3 nominations total","['Action', 'Mystery', 'Thriller']","['English', 'German', 'Turkish', 'Arabic']"
14,tt0108525,Wayne's World 2,1h 35m,PG-13,6.2,90K,60.0,The inseparable duo try to organize a rock con...,https://www.imdb.com/title/tt0108525/,"['Mike Myers', 'Bonnie Turner', 'Terry Turner']",...,"$13,516,699","$48,198,019","$48,197,805",1993-12-10,['United States'],"['United Methodist Church - 3205 D Street, La ...",['Paramount Pictures'],"Awards, 3 nominations total","['Buddy Comedy', 'Comedy', 'Music']","['English', 'Cantonese']"
33,tt0093277,Ironweed,2h 23m,R,6.7,10K,56.0,An alcoholic drifter spends Halloween in his h...,https://www.imdb.com/title/tt0093277/,['William Kennedy'],...,"$36,973","$7,393,346","$7,393,346",1988-02-12,['United States'],"['Albany, New York, USA']","['Home Box Office (HBO)', 'Keith Barish Produc...","Nominated for 2 Oscars, 2 wins & 4 nominations...",['Drama'],['English']
46,tt0814314,Seven Pounds,2h 3m,PG-13,7.6,320K,36.0,A man with a fateful secret embarks on an extr...,https://www.imdb.com/title/tt0814314/,['Grant Nieporte'],...,"$14,851,136","$169,748,929","$69,951,824",2008-12-19,['United States'],"['Pasadena, California, USA']","['Columbia Pictures', 'Relativity Media', 'Ove...","Awards, 4 wins & 7 nominations total","['Tragedy', 'Drama', 'Mystery', 'Thriller']","['English', 'Spanish']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63203,tt1531663,Everything Must Go,1h 37m,R,6.4,54K,65.0,"When an alcoholic relapses, causing him to los...",https://www.imdb.com/title/tt1531663/,"['Dan Rush', 'Raymond Carver']",...,"$791,676","$2,820,490","$2,711,643",2011-10-14,['United States'],['Aunt Chiladas - 7330 North Dreamy Draw Drive...,"['Temple Hill Entertainment', 'Cowtown Cinema ...","Awards, 1 nomination total","['Comedy', 'Drama']",['English']
63208,tt0108187,Son of the Pink Panther,1h 33m,PG,3.9,6.2K,33.0,"Charles Dreyfus encounters Jacques Gambrelli, ...",https://www.imdb.com/title/tt0108187/,"['Maurice Richlin', 'Blake Edwards', 'Madeline...",...,"$1,129,689","$2,438,031","$2,438,031",1993-08-27,"['Italy', 'United States']",['Jordan'],"['Filmauro', 'International Traders', 'United ...","Awards, 3 nominations total","['Farce', 'Slapstick', 'Comedy', 'Crime']","['English', 'Italian']"
63224,tt0272338,Punch-Drunk Love,1h 35m,R,7.3,185K,78.0,Socially frustrated Barry Egan calls a phone-s...,https://www.imdb.com/title/tt0272338/,['Paul Thomas Anderson'],...,"$367,203","$24,679,535","$17,844,216",2002-11-01,['United States'],"['Le Petit Chateau - 4615 Lankershim Blvd, Nor...","['New Line Cinema', 'Revolution Studios', 'Gho...","Awards, 14 wins & 37 nominations total","['Dark Comedy', 'Romantic Comedy', 'Comedy', '...",['English']
63230,tt0451221,The Elephant King,1h 32m,R,6.2,570,46.0,The story of two brothers who lead totally dif...,https://www.imdb.com/title/tt0451221/,['Seth Grossman'],...,"$15,959","$61,122","$22,251",2009-01-15,"['United States', 'Thailand']","['Chiang Mai, Thailand']","['Unison Films', 'De Warrenne Pictures']","Awards, 8 wins total","['Drama', 'Romance']","['English', 'Thai']"
63241,tt0297884,Far from Heaven,1h 47m,PG-13,7.3,50K,84.0,"In 1950s Connecticut, a flustered housewife fa...",https://www.imdb.com/title/tt0297884/,['Todd Haynes'],...,"$211,279","$29,027,914","$15,901,849",2003-01-10,"['United States', 'France']","[""Fabian's Ritz Theatre - 1148 E. Jersey Stree...","['Focus Features', 'Vulcan Productions', 'Kill...","Nominated for 4 Oscars, 102 wins & 96 nominati...","['Period Drama', 'Drama', 'Romance']",['English']

In [67]:
df_clean=df.dropna()

print('Rows:',df_clean.shape[0])
print('Columns:',df_clean.shape[1])

Rows: 6337
Columns: 23

In [68]:
df_clean=df_clean.filter(items=["title","genres","rating","votes","release_date"])
print(df_clean)

                             title  \
2      He's Just Not That Into You
4                          Unknown
14                 Wayne's World 2
33                        Ironweed
46                    Seven Pounds
...                            ...
63203           Everything Must Go
63208      Son of the Pink Panther
63224             Punch-Drunk Love
63230            The Elephant King
63241              Far from Heaven

                                                  genres  rating votes  \
2      ['Feel-Good Romance', 'Romantic Comedy', 'Come...     6.4  188K
4                      ['Action', 'Mystery', 'Thriller']     6.8  273K
14                   ['Buddy Comedy', 'Comedy', 'Music']     6.2   90K
33                                             ['Drama']     6.7   10K
46           ['Tragedy', 'Drama', 'Mystery', 'Thriller']     7.6  320K
...                                                  ...     ...   ...
63203                                ['Comedy', 'Drama']     6.4   54K
63208          ['Farce', 'Slapstick', 'Comedy', 'Crime']     3.9  6.2K
63224  ['Dark Comedy', 'Romantic Comedy', 'Comedy', '...     7.3  185K
63230                               ['Drama', 'Romance']     6.2   570
63241               ['Period Drama', 'Drama', 'Romance']     7.3   50K

      release_date
2       2009-02-06
4       2011-02-18
14      1993-12-10
33      1988-02-12
46      2008-12-19
...            ...
63203   2011-10-14
63208   1993-08-27
63224   2002-11-01
63230   2009-01-15
63241   2003-01-10

[6337 rows x 5 columns]

In [69]:
def clean_votes(v):
    if pd.isna(v):
        return 0
    v = v.replace(',', '')
    if 'K' in v:
        return int(float(v.replace('K','')) * 1000)
    elif 'M' in v:
        return int(float(v.replace('M','')) * 1_000_000)
    else:
        return int(v)

# Correct way: assign back to the column
df_clean['votes'] = df_clean['votes'].apply(clean_votes)

print(df_clean.head())

                          title  \
2   He's Just Not That Into You
4                       Unknown
14              Wayne's World 2
33                     Ironweed
46                 Seven Pounds

                                               genres  rating   votes  \
2   ['Feel-Good Romance', 'Romantic Comedy', 'Come...     6.4  188000
4                   ['Action', 'Mystery', 'Thriller']     6.8  273000
14                ['Buddy Comedy', 'Comedy', 'Music']     6.2   90000
33                                          ['Drama']     6.7   10000
46        ['Tragedy', 'Drama', 'Mystery', 'Thriller']     7.6  320000

   release_date
2    2009-02-06
4    2011-02-18
14   1993-12-10
33   1988-02-12
46   2008-12-19

In [70]:
df_clean['year']=pd.to_datetime(df_clean['release_date']).dt.year
print(df_clean.head())

                          title  \
2   He's Just Not That Into You
4                       Unknown
14              Wayne's World 2
33                     Ironweed
46                 Seven Pounds

                                               genres  rating   votes  \
2   ['Feel-Good Romance', 'Romantic Comedy', 'Come...     6.4  188000
4                   ['Action', 'Mystery', 'Thriller']     6.8  273000
14                ['Buddy Comedy', 'Comedy', 'Music']     6.2   90000
33                                          ['Drama']     6.7   10000
46        ['Tragedy', 'Drama', 'Mystery', 'Thriller']     7.6  320000

   release_date  year
2    2009-02-06  2009
4    2011-02-18  2011
14   1993-12-10  1993
33   1988-02-12  1988
46   2008-12-19  2008

In [74]:


df_clean['genres'] = df_clean['genres'].fillna('').str.replace(r"[\[\]'\"']", '', regex=True).str.split(',')
df_clean = df_clean.explode('genres').reset_index(drop=True)


df_clean['genres'] = df_clean['genres'].str.strip()
df_clean = df_clean[['title','genres','year','votes','rating']]

print(df_clean.head(10))

                         title             genres  year   votes  rating
0  He's Just Not That Into You  Feel-Good Romance  2009  188000     6.4
1  He's Just Not That Into You    Romantic Comedy  2009  188000     6.4
2  He's Just Not That Into You             Comedy  2009  188000     6.4
3  He's Just Not That Into You              Drama  2009  188000     6.4
4  He's Just Not That Into You            Romance  2009  188000     6.4
5                      Unknown             Action  2011  273000     6.8
6                      Unknown            Mystery  2011  273000     6.8
7                      Unknown           Thriller  2011  273000     6.8
8              Wayne's World 2       Buddy Comedy  1993   90000     6.2
9              Wayne's World 2             Comedy  1993   90000     6.2

In [72]:
df_clean.isna().any().any()

np.False_

In [75]:
print(df_clean)
#the dataset went from 6337 rows to 28572 rows because each genre got its own row, so dont get confused whoever is reading this

                             title             genres  year   votes  rating
0      He's Just Not That Into You  Feel-Good Romance  2009  188000     6.4
1      He's Just Not That Into You    Romantic Comedy  2009  188000     6.4
2      He's Just Not That Into You             Comedy  2009  188000     6.4
3      He's Just Not That Into You              Drama  2009  188000     6.4
4      He's Just Not That Into You            Romance  2009  188000     6.4
...                            ...                ...   ...     ...     ...
28567            The Elephant King              Drama  2009     570     6.2
28568            The Elephant King            Romance  2009     570     6.2
28569              Far from Heaven       Period Drama  2003   50000     7.3
28570              Far from Heaven              Drama  2003   50000     7.3
28571              Far from Heaven            Romance  2003   50000     7.3

[28572 rows x 5 columns]